# MkDocs configuration for Netlify builds

INHERIT: mkdocs-base.yml


site_url: "https://docs.percona.com/postgresql/"

theme:
  name: material
  custom_dir: _resourcepdf/overrides/

extra:
  analytics:
    provider: google
    property: G-J4J70BNH0G
