# MkDocs configuration for builds with material theme

INHERIT: mkdocs-base.yml

site_url: "https://docs.percona.com/postgresql/"

theme:
  name: material
  custom_dir: _resourcepdf/overrides/

extra:
  analytics:
    provider: google
    property: G-J4J70BNH0G

nav:
  - 'Home': 'index.md'
  - 'Percona Server for PostgreSQL': postgresql-server.md
  - get-help.md
  - Quickstart guide: quick-start.md
  - Get started: 
      - 1. Install:
          - Overview: installing.md 
          - Via apt: apt.md
          - Via yum: yum.md
          - From tarballs: tarball.md
          - Run in Docker: 
            - Overview: docker/docker.md
            - Upgrade in Docker: docker/docker-upgrade.md
            - 'Enable pg_tde for securing data at rest': docker/docker-enable-pg-tde.md
            - 'Enable stat-monitor for performance statistics': docker/docker-enable-pg-stat-monitor.md
          - enable-extensions.md
          - repo-overview.md
          - sboms.md
      - 2. Connect to PostgreSQL: connect.md
      - 3. Manipulate data in PostgreSQL: crud.md  
      - 4. What's next: whats-next.md 
  - Extensions:
      - 'Extensions': extensions.md
      - contrib.md
      - Percona-authored extensions: percona-ext.md
      - third-party.md
  - Solutions:
      - Overview: solutions.md
      - High availability:
          - 'Overview': 'solutions/high-availability.md'
          - solutions/ha-measure.md
          - 'Architecture': solutions/ha-architecture.md
          - Components:
            - 'ETCD': 'solutions/etcd-info.md'
            - 'Patroni': 'solutions/patroni-info.md'
            - 'HAProxy': 'solutions/haproxy-info.md'
            - 'pgBackRest': 'solutions/pgbackrest-info.md'
          - solutions/ha-components.md
          - Deployment:
              - 'Initial setup': 'solutions/ha-init-setup.md'
              - 'etcd setup': 'solutions/ha-etcd-config.md'
              - 'Patroni setup': 'solutions/ha-patroni.md'
              - solutions/pgbackrest.md
              - 'HAProxy setup': 'solutions/ha-haproxy.md'
          - solutions/ha-test.md
      - Backup and disaster recovery:
          - 'Overview': 'solutions/backup-recovery.md'
          - solutions/dr-pgbackrest-setup.md
      - Spatial data handling:
        - Overview: solutions/postgis.md
        - Deployment: solutions/postgis-deploy.md
        - Query spatial data: solutions/postgis-testing.md
        - Upgrade spatial database: solutions/postgis-upgrade.md
      - Authentication:
        - Overview: solutions/authentication/overview.md
        - OIDC authentication: solutions/authentication/oidc.md
        - LDAP authentication: solutions/authentication/ldap.md
  - Upgrade:
      - "Major upgrade": major-upgrade.md
      - minor-upgrade.md
      - migration.md
  - FAQ: faq.md  
  - Troubleshooting guide: troubleshooting.md
  - Uninstall: uninstalling.md
  - Release notes:
      - "Release notes index": release-notes/release-notes.md
      - "18.4.2 ({{date.18_4_2}})": release-notes/release-notes-v18.4.2.md
      - "18.4.1 ({{date.18_4_1}})": release-notes/release-notes-v18.4.1.md
      - "18.3.1 ({{date.18_3_1}})": release-notes/release-notes-v18.3.1.md
      - "2025":
        - "18.1.1 ({{date.18_1_1}})": release-notes/release-notes-v18.1.1.md
  - Reference:
      - Licensing: licensing.md
      - Versioning: versioning.md
      - Trademark policy: trademark-policy.md
  - legal-notice.md
