# MkDocs configuration for builds with material theme

INHERIT: mkdocs-base.yml

site_url: "https://docs.percona.com/postgresql/"

theme:
  name: material
  custom_dir: _resourcepdf/overrides/

extra:
  analytics:
    provider: google
    property: G-J4J70BNH0G
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thank you for your feedback! Help us improve by using our 
            <a href="https://docs.google.com/forms/d/1bkWACehjqlwA0AKf-qTJcXvYbOSYgze8iTPXjntqmNo/edit" target="_blank" rel="noopener">
            feedback form</a>.

nav:
  - 'Home': 'index.md'
  - get-help.md
  - Get started: 
      - Quickstart guide: installing.md
      - 1. Install: 
          - Via apt: apt.md
          - Via yum: yum.md
          - From tarballs: tarball.md
          - Run in Docker: docker.md
          - enable-extensions.md
          - repo-overview.md
      - 2. Connect to PostgreSQL: connect.md
      - 3. Manipulate data in PostgreSQL: crud.md  
      - 4. What's next: whats-next.md 
  - Extensions:
      - 'Extensions': extensions.md
      - contrib.md
      - Percona-authored extensions: percona-ext.md
      - third-party.md
  - Solutions:
      - Overview: solutions.md
      - High availability:
          - 'Overview': 'solutions/high-availability.md'
          - solutions/ha-measure.md
          - 'Architecture': solutions/ha-architecture.md
          - Components:
            - 'ETCD': 'solutions/etcd-info.md'
            - 'Patroni': 'solutions/patroni-info.md'
            - 'HAProxy': 'solutions/haproxy-info.md'
            - 'pgBackRest': 'solutions/pgbackrest-info.md'
          - solutions/ha-components.md
          - Deployment:
              - 'Initial setup': 'solutions/ha-init-setup.md'
              - 'etcd setup': 'solutions/ha-etcd-config.md'
              - 'Patroni setup': 'solutions/ha-patroni.md'
              - solutions/pgbackrest.md
              - 'HAProxy setup': 'solutions/ha-haproxy.md'
          - 'Testing': solutions/ha-test.md
      - Backup and disaster recovery:
          - 'Overview': 'solutions/backup-recovery.md'
          - solutions/dr-pgbackrest-setup.md
      - Spatial data handling:
        - Overview: solutions/postgis.md
        - Deployment: solutions/postgis-deploy.md
        - Query spatial data: solutions/postgis-testing.md
        - Upgrade spatial database: solutions/postgis-upgrade.md
      - LDAP authentication:
          - ldap.md
  - Upgrade:
      - "Major upgrade": major-upgrade.md
      - minor-upgrade.md
      - migration.md
  - Troubleshooting guide: troubleshooting.md
  - Uninstall: uninstalling.md
  - Release notes:
      - "Release notes index": release-notes/release-notes.md
      - "2025":
        - "16.9 Update": release-notes/release-notes-v16.9.upd.md
        - "16.9": release-notes/release-notes-v16.9.md
        - "16.8": release-notes/release-notes-v16.8.md
      - "2024 (versions 16.6 - 16.1 Update)":
        - "16.6": release-notes/release-notes-v16.6.md
        - "16.4": release-notes/release-notes-v16.4.md
        - "16.3": release-notes/release-notes-v16.3.md
        - "16.2": release-notes/release-notes-v16.2.md
        - "16.1 Update": release-notes/release-notes-v16.1.upd.md
      - "2023 (versions 16.1 - 16.0)":
        - "16.1": release-notes/release-notes-v16.1.md
        - "16.0 Update": release-notes/release-notes-v16.0.upd.md
        - "16.0": release-notes/release-notes-v16.0.md
  - Reference:
      - Telemetry: telemetry.md
      - Licensing: licensing.md
      - Trademark policy: trademark-policy.md

