name: Build Percona Distribution PostgreSQL 11 docs
on:
  push:
    branches: 
      - 11
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps: 
      #Pull the latest changes
      - name: Chekout code
        uses: percona-platform/checkout@v2
        with:
          fetch-depth: 0
      #Prepare the env
      - name: Set up Python
        uses: percona-platform/setup-python@v2
        with:
          python-version: '3.x'
      
      #Configure git
      - name: Configure git
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: |
          git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"
          git config user.name "GitHub Action"
          git config user.email "github-action@users.noreply.github.com"
          git config user.password "${ROBOT_TOKEN}"
          echo "GIT_USER=percona-platform-robot:${ROBOT_TOKEN}" >> $GITHUB_ENV

      #Set up MkDocs
      - name: Install MkDocs
        run: | 
          python3 -m pip install --upgrade pip     # install pip
          python3 -m pip install mkdocs            # install mkdocs 
          python3 -m pip install mkdocs-material   # install material theme
          python3 -m pip install mike              # install mike
          python3 -m pip install mkdocs-with-pdf   # install plugin for pdfs
          python3 -m pip install mkdocs-git-revision-date-plugin
          python3 -m pip install mkdocs-section-index
          python3 -m pip install mkdocs-macros-plugin
     
     #Set up PlantUML
      - name: Setup PlantUML dependencies
        run: |
          sudo apt install -y graphviz 
     
     # Deploy docs
      - name: Deploy docs
        run: |
          mike deploy 11 -F mkdocs-netlify.yml -b netlify -p
          mike retitle 11 "11.13" -b netlify -p
          